---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sentra-secret
  namespace: sentra
spec:
  encryptedData:
    AI_HUB_API_KEY: AgA+n1mKsL2vA+wBdBpuuVIt3cyJ9bt/mCDAmuP9jn+ZW9hdadM34ZVbxx7QYqoiCYCE8/al9BMGG/l5eZ07eEp+lmEVe3+azE1Itli9t2hw9tP7Ts85pTNxkRf9nr9/o69ftvqHAP5KHtA6aYEf4DqExLh/bYsLxl8Fsccq5iOjOWd7A5rO7ffIHdlbTp9qUZf4cRl362lJfYhagGmzJKA9ZTH0oknKJkgCPZ9t7Avfz3Za5ZHOFD1E5L8z9YFsDZKyGFUlpgbLt1SlgriqRXHJGfD2h0QRW/2qaaEZSvm/SOFSt03qOKNhD4RmXkiKtdC+giEsPvDWKhCDyjCp03pcGOGs8VFt0P5ximTN3v3kWnocW38piz5zcDoLtTlhX5Hwiy5RsdJGYFQ6Fu4kmzCguoeYi7rSVIRjzxju1XoFrUC0XhLUEy05KGCgKoz6wbLoh+fOLFLyFcKAoS9pF2wE5Lc5onNmGr89LKZJGOf8BZvbsFWfTDKFQfwlygIcLsGIZfjnumGluoHSsTnjQowFknSvppem9Zss3v3zDP06AP4hWqcTduHeY+Jq0HcmCv6zUCvm5LHW82ki55vgZ9+4irG5ZJf1P/QyLUnSYtvcRjIUTbndAQUfmUdi8Q0Lgx1/khvBSotRh90dmGtX01i5plNz5Gwvu2MLCy4/MaXI8NRxwvmc7sa5c7sMwwduLgiq0wBVrUJAN8wonpBTg5MUoZIMbU5VCryk
  template:
    metadata:
      name: sentra-secret
      namespace: sentra
    type: Opaque
